### ISSUE TITLE
UnicodeEncodeError when loading Araport11 GFF 

### ISSUE THREAD

**Issue by harmn** [candYgene/siga#28]
When converting the Araport11 GFF file to RDF, SIGA produces an error (at the write step):
UnicodeEncodeError: 'ascii' codec can't encode character u'\xf3' in position 6267791: ordinal not in range(128)

This is the used GFF file:
http://datacommons.cyverse.org/browse/iplant/home/araport/public_data/Araport11_Release_201606/annotation/Araport11_GFF3_genes_transposons.201606.gff.gz

Replacing this encoded character %C3%B3 with an "o" solves it.

**Comment by arnikz** [comment]
Thanks for reporting.
